-- © 2026 aiaiaiai · aiaiaiai.org
-- SPDX-License-Identifier: MPL-2.0

CREATE TABLE IF NOT EXISTS errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project TEXT NOT NULL,
    "type" TEXT NOT NULL,
    full_text TEXT NOT NULL,
    observed_at TEXT NOT NULL,
    received_at TEXT NOT NULL,
    CONSTRAINT errors_project_length CHECK (char_length(project) BETWEEN 1 AND 64),
    CONSTRAINT errors_type_length CHECK (char_length("type") BETWEEN 1 AND 128),
    CONSTRAINT errors_full_text_length CHECK (char_length(full_text) BETWEEN 1 AND 32768),
    CONSTRAINT errors_observed_at_length CHECK (char_length(observed_at) = 20),
    CONSTRAINT errors_received_at_length CHECK (char_length(received_at) = 20)
);

ALTER TABLE errors ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE errors FROM anon, authenticated;

CREATE INDEX IF NOT EXISTS errors_by_observed_at
ON errors (observed_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS errors_by_project_observed_at
ON errors (project, observed_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS errors_by_type_observed_at
ON errors ("type", observed_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS errors_by_received_at
ON errors (received_at);
