// © 2026 aiaiaiai · aiaiaiai.org
// SPDX-License-Identifier: MPL-2.0

export {
  createAvaiaMovementController,
  type AvaiaMovementController,
  type AvaiaMovementControllerOptions,
  type MovementState,
  type WorldPosition,
} from "./avaia-movement-controller";
export {
  createFailureNotice,
  type FailureKind,
  type FailureNotice,
  type FailureNoticeAction,
  type FailureNoticeTone,
  type FailureReport,
} from "./failure-notice";
export {
  ReadRuntimeReadiness,
  type CorePubDressLabelErrorCode,
  type CorePubDressLabelResult,
  type CoreRuntimePort,
  type CoreRuntimeStatus,
  type CoreUnavailableReason,
  type RuntimeReadiness,
} from "./core-runtime";
export {
  AcknowledgeRecoveryKey,
  AuthenticateNativeIdentity,
  BeginBrowserProviderAuthorization,
  ForgetRememberedBond,
  LinkBrowserProvider,
  LogoutNativeIdentity,
  ReadBrowserProviderContext,
  ReadNativeIdentityContext,
  ReadProviderIdentity,
  RegisterNativeIdentity,
  RegisterProviderIdentity,
  AVATAR_MODELS,
  ChooseAvatarModel,
  RenameAvaiaSlug,
  isAvatarModel,
  type AvatarModel,
  type AvatarModelResult,
  type PublishedAvatarModel,
  type StoredAvatarModel,
  RenamePubDressSlug,
  SetProviderPassword,
  ResolvePubDress,
  ResolvePubDressLabel,
  formatPubDress,
  parsePubDress,
  type BrowserIdentityProvider,
  type BrowserProviderAvailability,
  type BrowserProviderContextResult,
  type BrowserProviderLinkResult,
  type IdentityAccessPort,
  type IdentityProjection,
  type NativeAuthenticationResult,
  type NativeIdentityContextResult,
  type NativeMutationResult,
  type NativeRecoveryResult,
  type NativeRegistrationResult,
  type ProviderIdentityLookupResult,
  type ProviderPasswordHost,
  type ProviderPasswordResult,
  type ProviderRegistrationResult,
  type PubDressLabelResolutionResult,
  type PubDressRenameResult,
  type PubDressSelection,
  type PubDressResolutionResult,
} from "./identity-registration";
export {
  PUB_DRESS_LABEL_MAX_LENGTH,
  PUB_DRESS_URL_SUFFIX_MAX_LENGTH,
  PUB_DRESS_URL_ZONE,
  formatPubDressUrl,
  normalizePubDressUrlSuffix,
  projectCorePubDressLabel,
  projectCorePubDressLabelComposition,
  suggestPubDressUrlSuffix,
  type PubDressLabelComposition,
  type PubDressLabelDerivation,
  type PubDressLabelRejection,
  type PubDressLabelStem,
} from "./pub-dress-url";
